Upgrade installer to stretch and remove frr
open-switch/opx-onie-installer pull request #18
Opened 2018-06-01 20:43 UTC by theucke

Signed-off-by: Tyler Heucke <tyler.heucke@dell.com>

2018-06-01 22:24 UTC, heucke commented
Pull-request updated, HEAD is now 9602e24b9dfd08527b4ca9e233d0a3bc0898254e

2018-06-01 22:29 UTC, theucke commented
Pull-request updated, HEAD is now 55abb504d290f6ae30d34adef163f3c65374d76f

2018-06-04 21:48 UTC, theucke commented
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847986;msg=10

We'll have to upgrade the Docker image from Jessie to Stretch.

2018-06-05 18:22 UTC, theucke commented
Pull-request updated, HEAD is now 3d58e49fb30d486a405a6a8c3b5f6e0ffc88e57a

2018-06-06 02:50 UTC, theucke commented
Pull-request updated, HEAD is now 0b178707cdf8e93f36aff8abc2aba247f501908c

2018-06-06 02:54 UTC, theucke commented on release_bp/opx_debian_base_stretch.xml
> +  <xi:include href="repo/stretch.xml"/>
@GarrickHe @jeff-yin Still can't get bind9 from stretch-backports to install. We can go with no bind9 at all or use the regular bind9 (no backports). I opted for regular bind9 in this PR.

2018-06-06 03:36 UTC, theucke commented
Pull-request updated, HEAD is now b3ac1860a9c4a37890a05b2c5984c166bff92a5a

2018-06-06 04:00 UTC, theucke commented
@GarrickHe It's now failing at packages from the sync which haven't been published yet. The kernel is pinned to `4.9.82-1+deb9u3`. You can use my fork to test as we get packages from the sync published. Once all packages are published, this PR will build successfully and I can merge it.

2018-06-06 05:32 UTC, GarrickHe commented
@theucke No problem. I'll give it a try as soon as Howard puts up the new opx-platform-config packages.

2018-06-06 22:22 UTC, theucke commented
Pull-request updated, HEAD is now a487536bb8dea899f740462ab43c7e0f866e48a6

2018-06-07 18:55 UTC, theucke commented
Need to update `README.md` with new blueprint for Stretch.

2018-06-08 22:33 UTC, theucke commented
Pull-request updated, HEAD is now 99c9017c42c8127c26c5b93a2814a7abb265f6a6

2018-06-08 22:34 UTC, theucke commented
@jeff-yin I added `ftp` and `ntp` only to the Stretch blueprint.

2018-06-08 22:34 UTC, jeffyin-dell requested changes
Sorry, remove ftp. Spoke to @jghalam and he doesn't recommend adding FTP to the installer by default.

2018-06-08 22:35 UTC, theucke commented
Pull-request updated, HEAD is now 4bb37f808f7ef74c79500e5dee92706bc586aa6e

2018-06-08 22:37 UTC, theucke commented
Amended my commit, only leaving ntp.

2018-06-08 22:38 UTC, jeffyin-dell submitted a review, later dismissed

2018-06-20 19:35 UTC, theucke commented
Pull-request updated, HEAD is now 1b0fe1362613de1970db31571c8411031b1ab4bf

2018-06-20 20:43 UTC, theucke commented
Pull-request updated, HEAD is now 7af252db5a7b4c43db6a2cf757b2b8408971a9ce

2018-06-20 21:41 UTC, theucke commented
@jeff-yin I've set it up so that merging this PR will publish a Stretch Unstable installer to http://archive.openswitch.net/installers/unstable/Dell-EMC/PKGS_OPX-unstable-stretch-installer-x86_64.bin

2018-06-20 21:46 UTC, jeffyin-dell approved these changes

2018-06-20 21:48 UTC, merged