Added support ZTD feature
open-switch/opx-onie-installer pull request #31
Opened 2018-08-24 05:42 UTC by skg-net

Signed-off-by: Senthil Kumar Ganesan <skg.net.dev@gmail.com>

2018-08-24 18:12 UTC, heucke requested changes
The PR says "Added" ztd, but the contents of this PR seem to **enable** ztd. Please update the commit message if I am not mistaken.

2018-08-24 18:12 UTC, theucke commented on release_bp/OPX_dell_base_stretch.xml
> +  <inst_hook>95-enable-ztd-mode.postinst.sh</inst_hook>
Please add these in sorted order.

2018-08-24 18:14 UTC, theucke commented on release_bp/OPX_dell_base_stretch.xml
> +  <inst_hook>96-setup-ztd-dhclient.postinst.sh</inst_hook>
Is ztd not supported on Jessie?

2018-08-24 18:18 UTC, theucke commented on inst-hooks/03-disable-ztd-file.pre-upgrade.sh
> +rm -f /alt/root/hooks/95-enable-ztd-mode.postinst.sh
Is this directory created when ztd runs? Can you leave a comment regarding that? I don't see any `/alt` directory in the rootfs.

2018-08-24 21:35 UTC, skg-net commented
Pull-request updated, HEAD is now 47702d4f8f008e2b1bd287bdaacde1df520d62f5

2018-08-24 21:38 UTC, skg-net commented
@theucke Currently OPX doesn't support ZTD, we are adding the support. The one of the ONIE script is enabling that via config file. Addressed your other comments. Please take a look at it.

2018-08-24 21:40 UTC, heucke submitted a review, later dismissed

2018-08-24 21:41 UTC, theucke commented
Use squash and merge to combine your commit messages into one nice one.

2018-08-24 22:21 UTC, skg-net commented
Pull-request updated, HEAD is now b349ac98c33e4c8d2dcd3da909405b70ea035a39

2018-08-27 15:40 UTC, heucke submitted a review, later dismissed

2018-08-27 16:26 UTC, theucke commented
Are you planning on upgrading to the new rootfs later? https://github.com/open-switch/opx-onie-installer/blob/master/release_bp/rootfs_stretch.xml#L2

2018-08-27 18:29 UTC, skg-net commented
Pull-request updated, HEAD is now a962a09be9a0fdd2de227e08fbae7c4fd52fd1a3

2018-08-27 18:30 UTC, skg-net commented
Pull-request updated, HEAD is now 87a38d8afb0c154513ad9d3cb429948193491391

2018-08-27 18:31 UTC, skg-net commented
@theucke Updated to use the new rootfs.

2018-08-27 20:04 UTC, heucke approved these changes

2018-08-27 20:09 UTC, merged